# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TongueTwister.Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'JGProgressHUD', '~> 2.1'
  pod 'Material', '~> 3.1'
 pod 'Swinject', '~> 2.7'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'UIColor+Hex', '~> 1.0'
  pod 'TopViewControllerDetection', '~> 2.0'
  # Pods for TongueTwister.Swift

  target 'TongueTwister.SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TongueTwister.SwiftUITests' do
    # Pods for testing
  end

end
