# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Telecoms.Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
     pod 'JGProgressHUD', '~> 2.1'
    pod 'Material', '~> 3.1'
   pod 'Swinject', '~> 2.7'
  pod 'SVProgressHUD', '~> 2.2'
    pod 'UIColor+Hex', '~> 1.0'
    pod 'TopViewControllerDetection', '~> 2.0'
   pod 'GCDKit', '~> 2.1'
  pod 'Siesta', '~> 1.5'
    pod 'Toast-Swift', '~> 5.0'
    pod 'Alamofire', '~> 5.2'
   pod 'SwiftTimer', '~> 2.0'
   pod 'JSONParserSwift', '~> 1.1'
  pod 'NavigationDropdownMenu', '~> 5.0.0'

  # Pods for Telecoms.Swift

  target 'Telecoms.SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Telecoms.SwiftUITests' do
    # Pods for testing
  end

end
