# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataVault' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'PDSnackbar', '~> 0.2'
    pod 'RestKit', '~> 0.27'
    pod 'MaterialTextField', '~> 1.0'
    pod 'MaterialComponents', '~> 109.6'
    pod 'GoogleAPIClientForREST', '~> 1.4'
    pod 'GCDObjC', '~> 0.3'
    #pod 'MaterialControls', '~> 1.2'
  # Pods for DataVault

  target 'DataVaultTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataVaultUITests' do
    # Pods for testing
  end

end
