# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWAPIConsumer.Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'JGProgressHUD', '~> 2.1'
  pod 'Material', '~> 3.1'
  pod 'Resolver', '~> 1.1'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'UIColor+Hex', '~> 1.0'
  pod 'TopViewControllerDetection', '~> 2.0'
  pod 'GCDKit', '~> 2.1'
  pod 'Siesta', '~> 1.5'
  pod 'Toast-Swift', '~> 5.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftTimer', '~> 2.0'
  pod 'JSONParserSwift', '~> 1.1'
  pod 'DropDown', '~> 2.3'
  pod 'SwiftPopup', '~> 5.0'
  pod 'BottomDrawer', '~> 0.1'
  pod 'DrawerKit', '~> 0.7'
  pod 'NavigationDropdownMenu', '~> 5.0.0'
  pod 'ALRadialMenu', '~> 2.0'
  pod 'MaterialComponents', '~> 109.6'
  pod 'MPOProgressBar', '~> 0.0.1'
  
  # Pods for SWAPIConsumer.Swift
  
  target 'SWAPIConsumer.SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'SWAPIConsumer.SwiftUITests' do
    # Pods for testing
  end
  
end
